version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging into ECR
      - echo $AWS_DEFAULT_REGION $AWS_USERNAME
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username $AWS_USERNAME --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo start docker image build
      - echo $IMAGE_REPO_NAME
      - docker build -t $IMAGE_REPO_NAME:latest .
      - docker tag docker tag $IMAGE_REPO_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest      
  post_build:
    commands:
      - echo publish to ECR
      -  docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
